name: Survival
main: net.omniblock.survival.SurvivalPlugin
softdepend: [OmniNetwork, OmniRegions, ShopHandler]
version: 1.1.0
commands:
   dinero:
      description: Comando para ver tu dinero.
   money:
      description: Comando para ver tu dinero.
   lobby:
      description: Comando para volver al lobby principal.
   hub:
      description: Comando para volver al lobby principal.
   spawn:
      description: Comando para volver al spawn.
   tpa:
      description: Comando para teletransportarte a otro jugador.
   tpaccept:
      description: Comando para aceptar petición de tpa.
   tpdeny:
      description: Comando para denegar petición de tpa.
   back:
      description: Comando para regresar a una posición previa.
   pay:
      description: Comando para dar dinero.
   fly:
      description: Comando para volar.